sudo: required
dist: trusty

#services:
#  - docker

#addons:
#  ssh_known_hosts:
#    - github.com
#    - bitbucket.org

git:
  submodules: false

before_install:
  - sudo apt-get update && sudo apt-get install -qq -y build-essential cmake debhelper freeglut3-dev gtk-doc-tools libboost-filesystem-dev libboost-iostreams-dev libboost-program-options-dev libboost-random-dev libboost-regex-dev libboost-signals-dev libboost-system-dev libboost-thread-dev libcurl4-openssl-dev libfreeimage-dev libglew-dev libgtkmm-2.4-dev libltdl-dev libgsl0-dev libportmidi-dev libprotobuf-dev libprotoc-dev libqt4-dev libqwt-dev libtar-dev libtbb-dev libtinyxml-dev libxml2-dev ncurses-dev pkg-config protobuf-compiler python-matplotlib libvtk5.8 libvtk5-dev libvtk5-qt4-dev libqhull-dev python-pygame doxygen mercurial libglib2.0-dev openjdk-6-jdk python-dev gfortran f2c libf2c2-dev spacenavd libspnav-dev python-numpy python-scipy python-yaml python-vtk python-pip libgmp3-dev libblas-dev liblapack-dev libv4l-dev subversion libxmu-dev libusb-1.0-0-dev python-pymodbus graphviz curl libwww-perl libterm-readkey-perl libx264-dev libopenni-dev swig
  - pip install numpy
  - cd $TRAVIS_BUILD_DIR
  - sed -i 's/git@github.com:/https:\/\/github.com\//g' $TRAVIS_BUILD_DIR/.gitmodules 
  - sed -i 's/git@github.com:/https:\/\/github.com\//g' $TRAVIS_BUILD_DIR/catkin_ws/.gitmodules
  - sed -i 's/ssh:\/\/git@github.com\//https:\/\/github.com\//g' $TRAVIS_BUILD_DIR/software/externals/cmake/externals.cmake
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git submodule deinit -f catkin_ws/src/exotica-dev
  - rm -rf catkin_ws/src/exotica-dev
  - git add .gitmodules catkin_ws/.gitmodules software/externals/cmake/externals.cmake
  - git rm --cached -f catkin_ws/src/exotica-dev
  - git submodule update --init --recursive

install: true

script:
  - cd $TRAVIS_BUILD_DIR/software
  - source $TRAVIS_BUILD_DIR/software/config/drc_environment.sh
  - mkdir $TRAVIS_BUILD_DIR/software/externals/pod-build
  - cd $TRAVIS_BUILD_DIR/software/externals/pod-build
  - cmake .. -DBUILD_PRIVATE_EXTERNALS:BOOL=OFF -DUSE_SYSTEM_LCM:BOOL=OFF -DCMAKE_INSTALL_PREFIX:STRING=$TRAVIS_BUILD_DIR/software/build
  - cd $TRAVIS_BUILD_DIR/software/externals
  - make -j1
  - cd $TRAVIS_BUILD_DIR/software
  - make -j1
  #- docker pull openhumanoids/oh-distro-base:latest
  #- docker run -v $TRAVIS_BUILD_DIR:/home/test/oh-distro openhumanoids/oh-distro-base /bin/bash -c "sed -i 's/git@github.com:/https:\/\/github.com\//g' /home/test/oh-distro/.gitmodules && sed -i 's/git@github.com:/https:\/\/github.com\//g' /home/test/oh-distro/catkin_ws/.gitmodules && sed -i 's/ssh:\/\/git@github.com\//https:\/\/github.com\//g' /home/test/oh-distro/software/externals/cmake/externals.cmake  && cd /home/test/oh-distro && git submodule deinit catkin_ws/src/exotica-dev && rm -rf catkin_ws/src/exotica-dev && git submodule update --init --recursive && cd /home/test/oh-distro/software && source /home/test/oh-distro/software/config/drc_environment.sh &&  mkdir /home/test/oh-distro/software/externals/pod-build && cd /home/test/oh-distro/software/externals/pod-build && cmake .. -DBUILD_PRIVATE_EXTERNALS:BOOL=OFF && cd /home/test/oh-distro/software/externals && make -j8 && cd /home/test/oh-distro/software && make -j8"
